default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRES_USERNAME"]%>
  password: <%= ENV["POSTGRES_PASSWORD"]%>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary: &primary_development
    <<: *default
    database: stock_trader_app_v2_development
  queue:
    <<: *primary_development
    database: stock_trader_app_v2_development_queue
    migrations_paths: db/queue_migrate

test:
  primary: &primary_test
    <<: *default
    database: stock_trader_app_v2_test
  queue:
    <<: *primary_test
    database: stock_trader_app_v2_test_queue
    migrations_paths: db/queue_migrate

production:
  primary: &primary_production
    <<: *default
    database: stock_trader_app_v2_production
    username: stock_trader_app_v2
    password: <%= ENV["STOCK_TRADER_APP_V2_DATABASE_PASSWORD"] %>
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: stock_trader_app_v2_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: stock_trader_app_v2_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: stock_trader_app_v2_production_cable
    migrations_paths: db/cable_migrate