default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 5
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 3) %>
      polling_interval: 0.1

production:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 10
      polling_interval: 0.1

test:
  <<: *default

production:
  <<: *default

development:
  <<: *default