# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
development:
  update_stock_prices:
    class: UpdateStockPricesJob
    queue: default
    schedule: every 2 minutes
  update_daily_closing_prices_job:
    class: UpdateDailyClosingPricesJob
    queue: default
    schedule: "0 9 * * *"
    # schedule: every 24 hours
  update_daily_market_cap_job:
    class: UpdateDailyMarketCapJob
    queue: default
    schedule: "0 9 * * *"
    # schedule: every 24 hours

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  update_stock_prices:
    class: UpdateStockPricesJob
    queue: default
    schedule: every 2 minutes
  update_daily_closing_prices_job:
    class: UpdateDailyClosingPricesJob
    queue: default
    schedule: "0 5 * * *"
